language: python
python:
  - "2.7"
# install dependencies
before_install:
 - sudo apt-get install graphviz
install:
 - pip install -r requirements.txt
 - pip install -r test_requirements.txt
# command to run tests
script: nosetests
